const CFG=window.SIJI_CONFIG,$=id=>document.getElementById(id),modal=$("modal"),content=$("modalContent"),today=new Date(),iso=today.toISOString().slice(0,10);$("todayDate").textContent=today.toLocaleDateString("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"long"});
async function getJSON(p,f){try{let r=await fetch(p+"?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;return await r.json()}catch(e){return f}}
function key(x){return String(x||"").replaceAll(".","-").replaceAll("/","-").slice(0,10)}
function find(a){return Array.isArray(a)?a.find(x=>key(x.date||x.AA_YMD||x.calDate)===iso):null}
async function load(){let[m,s,t]=await Promise.all([getJSON("./data/meal.json",[]),getJSON("./data/schedule.json",[]),getJSON("./data/timetable.json",[])]);let a=find(m),b=find(s),c=find(t);$("meal").innerHTML=a?(a.menu||a.meal||a.DDISH_NM):"오늘 급식 정보가 없습니다.";$("schedule").textContent=b?(b.name||b.event||b.EVENT_NM||b.content):"오늘 학사일정이 없습니다.";$("timetable").textContent=c?(c.subject||c.subjects||"시간표 정보가 없습니다."):"오늘 시간표가 없습니다.";$("heroSummary").textContent=a||b||c?"오늘 학교 데이터가 준비되어 있습니다.":"오늘 표시할 학교 데이터가 없습니다."}
function openModal(x){content.innerHTML=x;modal.classList.add("show")}function closeModal(){modal.classList.remove("show")}window.closeModal=closeModal;
async function openNews(){let d=await getJSON("./data/news.json",[]);openModal("<h2>학교 뉴스</h2>"+(d.length?d.map(n=>`<div class="news-item"><b>${esc(n.title)}</b><br><a href="${url(n.url)}" target="_blank">자세히 보기 →</a></div>`).join(""):`<p>등록된 뉴스가 없습니다.</p><a class="btn" href="${CFG.SCHOOL_WEBSITE}" target="_blank">공식 학교 홈페이지</a>`))}window.openNews=openNews;
async function openData(type){let m={meal:["급식","meal.json"],schedule:["학사일정","schedule.json"],timetable:["시간표","timetable.json"]}[type],d=await getJSON("./data/"+m[1],[]);openModal("<h2>"+m[0]+"</h2>"+(d.length?d.slice(0,30).map(x=>`<div class="news-item"><b>${esc(x.date||x.AA_YMD||"")}</b><br>${esc(x.menu||x.name||x.event||x.subject||x.content||x.DDISH_NM||"")}</div>`).join(""):"<p>데이터가 없습니다. GitHub Actions를 확인하세요.</p>"))}window.openData=openData;
function openTool(t){if(t==="calculator")openModal(`<h2>계산기</h2><input id="calc" class="tool-input" placeholder="예: (12+8)*3"><button class="btn" onclick="calc()">계산</button><div id="result" class="tool-result"></div>`);if(t==="timer")openTimer();if(t==="random")openModal(`<h2>랜덤 뽑기</h2><textarea id="items" class="tool-input" rows="5" placeholder="한 줄에 하나"></textarea><button class="btn" onclick="pick()">뽑기</button><div id="result" class="tool-result"></div>`);if(t==="color")openModal(`<h2>색상 도구</h2><input id="color" type="color" value="#2864e8" style="width:100%;height:70px"><div id="result" class="tool-result">#2864E8</div>`);if(t==="notes")openModal(`<h2>메모장</h2><textarea id="notes" class="tool-input" rows="12">${esc(localStorage.getItem("siji_notes")||"")}</textarea><button class="btn" onclick="saveNotes()">저장</button>`)}window.openTool=openTool;
function calc(){try{$("result").textContent=Function('"use strict";return('+$("calc").value+')')()}catch{$("result").textContent="계산식을 확인하세요."}}function pick(){let a=$("items").value.split("\n").map(x=>x.trim()).filter(Boolean);$("result").textContent=a.length?a[Math.floor(Math.random()*a.length)]:"항목을 입력하세요."}function saveNotes(){localStorage.setItem("siji_notes",$("notes").value);$("result")?.remove()}let sec=1500,id;function openTimer(){openModal(`<h2>집중 타이머</h2><div id="clock" class="timer">25:00</div><div class="tool-actions"><button onclick="startTimer()">시작</button><button onclick="pauseTimer()">일시정지</button><button onclick="resetTimer()">초기화</button></div>`)}function render(){if($("clock"))$("clock").textContent=String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}function startTimer(){if(id)return;id=setInterval(()=>{if(sec<=0){pauseTimer();alert("집중 시간이 끝났습니다!");return}sec--;render()},1000)}function pauseTimer(){clearInterval(id);id=null}function resetTimer(){pauseTimer();sec=1500;render()}window.startTimer=startTimer;window.pauseTimer=pauseTimer;window.resetTimer=resetTimer;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function url(u){try{let x=new URL(u,location.href);return /^https?:$/.test(x.protocol)?x.href:"#"}catch{return "#"}}
async function posts(){let e=$("posts");if(!CFG.SUPABASE_ANON_KEY||CFG.SUPABASE_ANON_KEY.startsWith("PASTE_")){e.innerHTML='<div class="empty">config.js에 Supabase anon/publishable key를 설정하세요.</div>';return}try{let r=await fetch(CFG.SUPABASE_URL+"/rest/v1/posts?select=*&order=created_at.desc",{headers:{apikey:CFG.SUPABASE_ANON_KEY,Authorization:"Bearer "+CFG.SUPABASE_ANON_KEY}});let d=await r.json();e.innerHTML=d.length?d.map(p=>`<article class="post"><h3>${esc(p.title)}</h3><p>${esc(p.content)}</p></article>`).join(""):'<div class="empty">아직 게시글이 없습니다.</div>'}catch{e.innerHTML='<div class="empty">커뮤니티 데이터를 불러오지 못했습니다.</div>'}}function openPost(){openModal("<h2>글쓰기</h2><p>Supabase 인증 연결 후 게시글 작성 기능을 사용할 수 있습니다.</p>")}window.openPost=openPost;$("loginBtn").onclick=()=>location.href="./login.html";load();posts();